extends Node3D


# Dictionary of expressions to blend-shapes available on the face model
const _expressions := {
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_BROW_LOWERER_L : XRFaceTrackingProvider.FT_BROW_DOWN_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_BROW_LOWERER_R : XRFaceTrackingProvider.FT_BROW_DOWN_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHEEK_PUFF_L : XRFaceTrackingProvider.FT_CHEEK_PUFF_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHEEK_PUFF_R : XRFaceTrackingProvider.FT_CHEEK_PUFF_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHEEK_RAISER_L : XRFaceTrackingProvider.FT_CHEEK_SQUINT_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHEEK_RAISER_R : XRFaceTrackingProvider.FT_CHEEK_SQUINT_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHEEK_SUCK_L : XRFaceTrackingProvider.FT_CHEEK_SUCK_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHEEK_SUCK_R : XRFaceTrackingProvider.FT_CHEEK_SUCK_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHIN_RAISER_B : XRFaceTrackingProvider.FT_MOUTH_RAISER_LOWER,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_CHIN_RAISER_T : XRFaceTrackingProvider.FT_MOUTH_RAISER_UPPER,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_DIMPLER_L : XRFaceTrackingProvider.FT_MOUTH_DIMPLE_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_DIMPLER_R : XRFaceTrackingProvider.FT_MOUTH_DIMPLE_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_CLOSED_L : XRFaceTrackingProvider.FT_EYE_CLOSED_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_CLOSED_R : XRFaceTrackingProvider.FT_EYE_CLOSED_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_DOWN_L : XRFaceTrackingProvider.FT_EYE_LOOK_DOWN_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_DOWN_R : XRFaceTrackingProvider.FT_EYE_LOOK_DOWN_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_LEFT_L : XRFaceTrackingProvider.FT_EYE_LOOK_OUT_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_LEFT_R : XRFaceTrackingProvider.FT_EYE_LOOK_IN_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_RIGHT_L : XRFaceTrackingProvider.FT_EYE_LOOK_IN_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_RIGHT_R : XRFaceTrackingProvider.FT_EYE_LOOK_OUT_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_UP_L : XRFaceTrackingProvider.FT_EYE_LOOK_UP_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_EYES_LOOK_UP_R : XRFaceTrackingProvider.FT_EYE_LOOK_UP_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_JAW_DROP : XRFaceTrackingProvider.FT_JAW_OPEN,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_JAW_SIDEWAYS_LEFT : XRFaceTrackingProvider.FT_JAW_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_JAW_SIDEWAYS_RIGHT : XRFaceTrackingProvider.FT_JAW_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_JAW_THRUST : XRFaceTrackingProvider.FT_JAW_FORWARD,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_CORNER_DEPRESSOR_L : XRFaceTrackingProvider.FT_MOUTH_FROWN_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_CORNER_DEPRESSOR_R : XRFaceTrackingProvider.FT_MOUTH_FROWN_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_CORNER_PULLER_L : XRFaceTrackingProvider.FT_MOUTH_SMILE_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_CORNER_PULLER_R : XRFaceTrackingProvider.FT_MOUTH_SMILE_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_FUNNELER_LB : XRFaceTrackingProvider.FT_LIP_FUNNEL_LOWER_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_FUNNELER_LT : XRFaceTrackingProvider.FT_LIP_FUNNEL_UPPER_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_FUNNELER_RB : XRFaceTrackingProvider.FT_LIP_FUNNEL_LOWER_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_FUNNELER_RT : XRFaceTrackingProvider.FT_LIP_FUNNEL_UPPER_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_PRESSOR_L : XRFaceTrackingProvider.FT_MOUTH_PRESS_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_PRESSOR_R : XRFaceTrackingProvider.FT_MOUTH_PRESS_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_STRETCHER_L : XRFaceTrackingProvider.FT_MOUTH_STRETCH_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_STRETCHER_R : XRFaceTrackingProvider.FT_MOUTH_STRETCH_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_SUCK_LB : XRFaceTrackingProvider.FT_LIP_SUCK_LOWER_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_SUCK_LT : XRFaceTrackingProvider.FT_LIP_SUCK_UPPER_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_SUCK_RB : XRFaceTrackingProvider.FT_LIP_SUCK_LOWER_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_SUCK_RT : XRFaceTrackingProvider.FT_LIP_SUCK_UPPER_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_TIGHTENER_L : XRFaceTrackingProvider.FT_MOUTH_TIGHTENER_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIP_TIGHTENER_R : XRFaceTrackingProvider.FT_MOUTH_TIGHTENER_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LIPS_TOWARD : XRFaceTrackingProvider.FT_MOUTH_CLOSED,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LOWER_LIP_DEPRESSOR_L : XRFaceTrackingProvider.FT_MOUTH_LOWER_DOWN_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_LOWER_LIP_DEPRESSOR_R : XRFaceTrackingProvider.FT_MOUTH_LOWER_DOWN_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_MOUTH_LEFT : XRFaceTrackingProvider.FT_MOUTH_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_MOUTH_RIGHT : XRFaceTrackingProvider.FT_MOUTH_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_NOSE_WRINKLER_L : XRFaceTrackingProvider.FT_NOSE_SNEER_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_NOSE_WRINKLER_R : XRFaceTrackingProvider.FT_NOSE_SNEER_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_OUTER_BROW_RAISER_L : XRFaceTrackingProvider.FT_BROW_OUTER_UP_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_OUTER_BROW_RAISER_R : XRFaceTrackingProvider.FT_BROW_OUTER_UP_RIGHT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_UPPER_LIP_RAISER_L : XRFaceTrackingProvider.FT_MOUTH_UPPER_UP_LEFT,
	OpenXRFbFaceTrackingExtensionWrapper.EXPRESSION_UPPER_LIP_RAISER_R : XRFaceTrackingProvider.FT_MOUTH_UPPER_UP_RIGHT,
}


# Face mesh
@onready var face : MeshInstance3D = $Face/Face

# Face tracking provider
var _provider := XRFaceTrackingProvider.new()


func _ready() -> void:
	# Register the face tracking provider
	XRServer.add_face_tracking_provider("/user/head", _provider)


# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(_delta : float) -> void:
	# Get the weights
	var weights := OpenXRFbFaceTrackingExtensionWrapper.get_weights()
	if weights.is_empty():
		return

	# Populate the provider
	for i in _expressions:
		_provider.set_blend_shape(_expressions[i], weights[i])
